### ISSUE TITLE
Gather information for EDDE updates

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/ose-equity-tool-etl#36]
Coordinate with Winnie and data engineering to gather information required EDDE 2024 data updates, including which variables will have data from a new year, and top and bottom codings.

**Comment by dhochbaum-dcp** [comment]
**Sections with updated data:**
Housing Affordability, Quality, and Security: 

- Table 3.09 Residential Evictions, 
- Table 3.10 Number of Individuals in Shelter System by Last Address, 
- Table 3.11 Income-Restricted Housing, 
- Table 3.12 Population in NYC Housing Authority Housing

Housing Production

- Table 4.01 Change in Housing Units,
- Table 4.02 Homes with New or Extended Affordability Requirements by AMI* Band

Quality of Life & Access to Opportunity

- Table 5.08 Access to Jobs
- Table 5.09 Access to Transit
- Table 5.14 Open Space - Park Access

**New variables:**
None

**Comment by dhochbaum-dcp** [comment]
"There's top and bottom codings for the census/ACS related data but we're not changing those this update"

For reference, last time they were:
2017-2021 Top- & Bottom-Code values:

- Median Age – top-code = 85 (show as 85+)
- Median Household Income – top-code = 200,000 (show as 200,000+), bottom-code = 9,999 (show as 10,000-)
- Median Wages (all) – top-code =  200,000 (show as 200,000+), bottom-code = 9,999 (show as 10,000-)
- Median Value – top-code = 2,000,000 (show as (2,000,000+)
- Median Gross Rent – top-code =  3,500 (show as 3,500+)

 
2008-2012 Inflated Top- & Bottom-Code values (2021 $):

- Median Age – unchanged (85+)
- Median Household Income – new top-code = 236,000+ , new bottom-code = 12,000-
- Median Wages (all) – new top-code = 236,000+ , new bottom-code = 12,000-
- Median Value – new top-code = 1,182,000+
- Median Gross Rent – new top-code = 2,300+

[Top- and Bottom-Coded Values_ACS 2017-2021 and 2008-2012.xlsx](https://github.com/NYCPlanning/ose-equity-tool-etl/files/15080238/Top-.and.Bottom-Coded.Values_ACS.2017-2021.and.2008-2012.xlsx)

**Comment by dhochbaum-dcp** [comment]
Of the sections with updated data, only Table 3.10 contains change over time data.  There are two calculated variables that need to be updated, `dhs_shelter_change_count` and `dhs_shelter_change_count_pct`.
